//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab5_Client.Ensure_Agent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ensure_Agent.IEnsure_Agent")]
    public interface IEnsure_Agent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsure_Agent/AddClaim", ReplyAction="http://tempuri.org/IEnsure_Agent/AddClaimResponse")]
        string AddClaim(out decimal cost, int sum_of_ensure, System.DateTime start_data, System.DateTime end_data, int group, string passport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnsure_AgentChannel : Lab5_Client.Ensure_Agent.IEnsure_Agent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ensure_AgentClient : System.ServiceModel.ClientBase<Lab5_Client.Ensure_Agent.IEnsure_Agent>, Lab5_Client.Ensure_Agent.IEnsure_Agent {
        
        public Ensure_AgentClient() {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ensure_AgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddClaim(out decimal cost, int sum_of_ensure, System.DateTime start_data, System.DateTime end_data, int group, string passport) {
            return base.Channel.AddClaim(out cost, sum_of_ensure, start_data, end_data, group, passport);
        }
    }
}
