//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensure_Agent.FinanceDep {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Insurance", Namespace="http://schemas.datacontract.org/2004/07/Lab_5")]
    [System.SerializableAttribute()]
    public partial class Insurance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InsuranceSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ensure_Agent.FinanceDep.RiskGroupType RiskGrupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InsuranceSum {
            get {
                return this.InsuranceSumField;
            }
            set {
                if ((this.InsuranceSumField.Equals(value) != true)) {
                    this.InsuranceSumField = value;
                    this.RaisePropertyChanged("InsuranceSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ensure_Agent.FinanceDep.RiskGroupType RiskGrup {
            get {
                return this.RiskGrupField;
            }
            set {
                if ((this.RiskGrupField.Equals(value) != true)) {
                    this.RiskGrupField = value;
                    this.RaisePropertyChanged("RiskGrup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RiskGroupType", Namespace="http://schemas.datacontract.org/2004/07/Lab_5")]
    public enum RiskGroupType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        P4 = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinanceDep.IFinanceDep")]
    public interface IFinanceDep {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceDep/CheckFinance", ReplyAction="http://tempuri.org/IFinanceDep/CheckFinanceResponse")]
        bool CheckFinance(decimal insuranceSum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinanceDep/DetermineCostOfInsurance", ReplyAction="http://tempuri.org/IFinanceDep/DetermineCostOfInsuranceResponse")]
        decimal DetermineCostOfInsurance(Ensure_Agent.FinanceDep.Insurance insurance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinanceDepChannel : Ensure_Agent.FinanceDep.IFinanceDep, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinanceDepClient : System.ServiceModel.ClientBase<Ensure_Agent.FinanceDep.IFinanceDep>, Ensure_Agent.FinanceDep.IFinanceDep {
        
        public FinanceDepClient() {
        }
        
        public FinanceDepClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinanceDepClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceDepClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinanceDepClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckFinance(decimal insuranceSum) {
            return base.Channel.CheckFinance(insuranceSum);
        }
        
        public decimal DetermineCostOfInsurance(Ensure_Agent.FinanceDep.Insurance insurance) {
            return base.Channel.DetermineCostOfInsurance(insurance);
        }
    }
}
