//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnsureCommitet.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IEnsure_Agent")]
    public interface IEnsure_Agent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsure_Agent/GetData", ReplyAction="http://tempuri.org/IEnsure_Agent/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsure_Agent/GetData", ReplyAction="http://tempuri.org/IEnsure_Agent/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsure_Agent/AddClaim", ReplyAction="http://tempuri.org/IEnsure_Agent/AddClaimResponse")]
        string AddClaim(int sum_of_ensure, int period, int group, string passport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsure_Agent/AddClaim", ReplyAction="http://tempuri.org/IEnsure_Agent/AddClaimResponse")]
        System.Threading.Tasks.Task<string> AddClaimAsync(int sum_of_ensure, int period, int group, string passport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnsure_AgentChannel : EnsureCommitet.ServiceReference2.IEnsure_Agent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ensure_AgentClient : System.ServiceModel.ClientBase<EnsureCommitet.ServiceReference2.IEnsure_Agent>, EnsureCommitet.ServiceReference2.IEnsure_Agent {
        
        public Ensure_AgentClient() {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ensure_AgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ensure_AgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string AddClaim(int sum_of_ensure, int period, int group, string passport) {
            return base.Channel.AddClaim(sum_of_ensure, period, group, passport);
        }
        
        public System.Threading.Tasks.Task<string> AddClaimAsync(int sum_of_ensure, int period, int group, string passport) {
            return base.Channel.AddClaimAsync(sum_of_ensure, period, group, passport);
        }
    }
}
