//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ensure_Agent.EnsureCommitet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EnsureCommitet.IEnsureCommitet")]
    public interface IEnsureCommitet {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsureCommitet/Request", ReplyAction="http://tempuri.org/IEnsureCommitet/RequestResponse")]
        int Request(string id, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsureCommitet/Is_Crime", ReplyAction="http://tempuri.org/IEnsureCommitet/Is_CrimeResponse")]
        bool Is_Crime(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnsureCommitet/Enought_Money", ReplyAction="http://tempuri.org/IEnsureCommitet/Enought_MoneyResponse")]
        bool Enought_Money(int amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnsureCommitetChannel : Ensure_Agent.EnsureCommitet.IEnsureCommitet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnsureCommitetClient : System.ServiceModel.ClientBase<Ensure_Agent.EnsureCommitet.IEnsureCommitet>, Ensure_Agent.EnsureCommitet.IEnsureCommitet {
        
        public EnsureCommitetClient() {
        }
        
        public EnsureCommitetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnsureCommitetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnsureCommitetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnsureCommitetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Request(string id, int amount) {
            return base.Channel.Request(id, amount);
        }
        
        public bool Is_Crime(string id) {
            return base.Channel.Is_Crime(id);
        }
        
        public bool Enought_Money(int amount) {
            return base.Channel.Enought_Money(amount);
        }
    }
}
